name: DR2 Tag and pre deploy
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: write
jobs:
  pre-deploy:
    uses: nationalarchives/dr2-github-actions/.github/workflows/lambda_build.yml@917201e254f112ff041b952dae76ef767cae7378
    with:
      repo-name: dr2-ip-lock-checker
      artifact-name: ip_lock_checker_lambda
      artifact-file-type: zip
      artifact-path: .
      build-command: |
        mkdir package
        pip install --target ./package -r requirements-runtime.txt
        cd package
        zip -r ../ip_lock_checker_lambda.zip .
        cd ..
        zip ip_lock_checker_lambda.zip lambda_function.py
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  deploy:
    needs: pre-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
      - run: gh workflow run deploy.yml -f environment=intg -f to-deploy=${{ needs.pre-deploy.outputs.next-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
